language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"

install: pip install -r requirements.txt --use-mirrors

before_script: python setup.py pep8
script: python setup.py test

notifications:
  email:
    - tomaz+travisci@tomaz.me
    - ilgizisl@gmail.com
